apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: result
  name: result
spec:
  ports:
  - name: 5001-80
    port: 5001
    protocol: TCP
    targetPort: 80
  selector:
    app: result
  type: LoadBalancer
status:
  loadBalancer: {}
